### PR TITLE
 Display non-default phone nos / email addresses in contact list if they're the only ones #90

### LINKED ISSUE #90: Display non-default phone nos / email addresses in contact list if they're the only ones
If there is only one phone number or email address for a contact, but it isn't explicitely set as default number or address, it is not shown in the contact list. 
After import from the contact app my contacts are all without "defaults", so no data is shown in the list.
## 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26752374-display-non-default-phone-nos-email-addresses-in-contact-list-if-they-re-the-only-ones?utm_campaign=plugin&utm_content=tracker%2F19713444&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F19713444&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pravussum**
fixes #90.

### CODE REVIEW

**Comment by deMattin** [comment]
Nice, but would it be possible to mark this mail addresses and phone nos like showing them italic or something like this?
So it could be possible to get the difference between favorites and automatic displayed informations.

**Comment by pravussum** [comment]
I thought about your need for recognising non-revised contacts: what about importing them into a separate addressbook (say "incoming" or the like) and moving revised contacts to the default addressbook?
I just really do think the average user can't be bothered to revise all his contacts he just imported from mother Google.

**Comment by deMattin** [comment]
Might be a workaround solution but in this case you are forced to review any contact directly after importing because another temporary address book is not synched to phone or other connectors and so on.
With this pull you make it more easy for anybody, not maintaining his contacts but make it harder, for someone, who wants to revise and check any imported contact.

I really like that not showing (favorites) data in card view, if not set manually. And I use this and check contacts little by little - not all of my contacts are checked, yet.
For me it's a feature and not a bug, that is to be fixed.

A mark for automatic view favorites in whatever style would satisfy both needs. But I also have no idea how to get this easily.
May be something like this possible: "If no favorite set, use style italic for Displaying nos and mail?

Let's see, what @libasys thinks and does...

**Comment by pravussum** [comment]
obsolete.

**Pull request closed without merging**
