### PR TITLE
fix icon, and it not showing in apps management

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review  @libasys @DeepDiver1975 @sahne123 @MorrisJobke @schiesbn @lukasreschke

### CODE REVIEW

**Comment by jancborchardt** [comment]
Um @libasys, any reaction please? ;D

**Comment by phsc84** [comment]
@libasys Is there a specific reason, why you are hesitating to accept this pull request?

**Comment by libasys** [comment]
can be closed i added complete new icons and rename the files! thanks for your help!

**Comment by jancborchardt** [comment]
The app icon you did uses color, unlike any other app icon. Yes, we don’t have any guidelines for that published but app icons should be fully white as to not grab unneeded attention.

@libasys again, this is quite an opaque development process you do with your apps. I want to help, and here I am with a _very simple_ pull request not tended to for 2 months. And then subsequently closed. Exactly the complaints you had with the current Calendar app …

I can’t stress it enough: We need to work together here in an open process. Otherwise our Contacts and Calendar apps will never have proper quality.

**Pull request closed without merging**
